# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable y would like, and they will be accessible
#  the templates via {{ site.myvariable }}.
tie: 'Flightdeck: A Scaffold for Jekyll'
email: client-email@client_domain.com
description: Flightdeck is a scaffold & starter project for Jekyll that uses an opinionated workflow.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

### SEO
#image: /assets/images/open_graph_image.png
social:
  twitter: github
  instagram: github
  github: github

include_rss_feed: false

gaCode: # UA-XXXXXXXX-XX

### Build settings
markdown: kramdown
# plugins:

keep_files: # When clobbering the site destination, keep the selected files.
  - assets

### Exclude directories and/or files from the conversion.
exclude:
  - LICENSE
  - README.md
  - flightdeck.manifest.js
  - gulpfile.js
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json # for those that use npm
  - yarn.lock # for those that use yarn
  - Gemfile
  - Gemfile.lock
  - vendor
